version: '3.4'

services:
  backend-production:
    image: backend-production
    build:
      context: .
      dockerfile: ./Dockerfile.Server
    command: ["bash","run/run.sh","-e production", "-m", "-c"]
    env_file:
      - .env.production
    ports:
      - 127.0.0.1:8002:8000
    volumes:
      - .:/app
    networks:
      - production-network

  db-production:
    image: postgres:15
    env_file:
     - .env.production
    ports:
      - 127.0.0.1:5434:5432
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    networks:
      - production-network

  redis-production:
    image: redis:7
    env_file:
      - .env.production
    ports:
      - 127.0.0.1:6381:6379
    volumes:
      - ./redis/data/:/var/lib/redis/data/
      - ./docker/docker-service-redis-start.sh:/usr/local/bin/docker-service-redis-start.sh
    entrypoint: /usr/local/bin/docker-service-redis-start.sh # used to pass PW from environment variable change things there if needed
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - production-network

  minio-production:
    image: minio/minio
    container_name: minio-production
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
      - ./docker/docker-service-minio-start.sh:/usr/local/bin/docker-service-minio-start.sh
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:4568:9000"
    entrypoint: /usr/local/bin/docker-service-minio-start.sh
    networks:
      - production-network

networks:
  production-network: