# Generated by Django 4.2.7 on 2024-10-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('token', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='code_General.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='code_General.user')),
            ],
        ),
    ]
