# Generated by Django 4.2.7 on 2024-10-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_General', '0002_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code_General.organization'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code_General.user'),
        ),
    ]
