# Generated by Django 4.2.7 on 2024-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_General', '0003_alter_apitoken_organization_alter_apitoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.CharField(max_length=513, primary_key=True, serialize=False)),
                ('eventType', models.CharField(max_length=200)),
                ('userHashedID', models.CharField(max_length=513)),
                ('eventData', models.JSONField()),
                ('createdWhen', models.DateTimeField(auto_now_add=True)),
                ('triggerEvent', models.BooleanField()),
            ],
            options={
                'ordering': ['createdWhen'],
                'indexes': [models.Index(fields=['userHashedID'], name='event_user_idx')],
            },
        ),
    ]
