# Generated by Django 4.2.7 on 2024-11-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_General', '0004_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='GB_event_user_idx',
            old_name='event_user_idx',
        ),
    ]
