# Generated by Django 4.2.7 on 2025-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_General', '0005_rename_event_user_idx_gb_event_user_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
